### ISSUE TITLE
Is this in the free allowance of fly.io?

### ISSUE THREAD

**Issue by eylenburg** [pcrockett/mollysocket-fly#1]
After starting the service as described this is shown in my fly.io Dashboard:

![Screenshot_20240110_093216](https://github.com/pcrockett/mollysocket-fly/assets/84839316/843295ee-b11c-4d57-8559-6935c0e885ab)

Meanwhile the [free resources](https://fly.io/docs/about/pricing/#free-allowances) are:

> Resources included for free on all plans:
>    Up to 3 shared-cpu-1x 256mb VMs
>    3GB persistent volume storage (total)
>    160GB outbound data transfer 
> Additional resources are billed at the usage-based pricing detailed below.

Are you sure this is within the free allowance as the readme implies?

**Comment by pcrockett** [comment]
Good question. This should be added to the readme.

So, looking at the Machines page, it does look like it's using more resources than the free tier allows.

However if you look at the Apps page, you should see something like this:

![image](https://github.com/pcrockett/mollysocket-fly/assets/1114385/bd9ffc1f-88ec-4680-bfad-06d2f65085fe)

If you click on that app, you'll see an explanation:

![image](https://github.com/pcrockett/mollysocket-fly/assets/1114385/6ca46a35-900f-4be5-8645-e68bb5f16e51)

That said, it does look like I'm _technically_ racking up charges for my normal app VM. But I got an email about this at the end of the month:

>  Good news from Fly.io! We don’t collect bills smaller than $5.00.
>
> This month, your bill of $0.49 falls below that threshold, so we’re discounting it by 100%. 

So I think when they say, "free tier," they actually mean "we don't charge you if your bill is less than $5."

**Comment by pcrockett** [comment]
Added notes to README about this. Will keep this issue open for a while; after a few months, if my assumptions are correct, we can close it.

**Comment by eylenburg** [comment]
I guess to be on the save side you could also put `memory_mb = 256` in the .toml file. Although I'm not sure how much RAM Mollysocket really needs and what would happen if it wants more RAM - would it crash or just slow down?

**Comment by pcrockett** [comment]
Good point. I reduced to 256 MiB (the minimum that Fly allows), and for all running processes, it's still using a third of that amount.

If you want to keep an eye on it, you can connect to the machine with `flyctl ssh console`, and then

```bash
sudo apt update && sudo apt install --yes htop && htop
```

The VM doesn't have a swap partition, so if we ran out of memory, it would crash. It would be doable to use the [swap_size_mb](https://fly.io/docs/reference/configuration/#swap_size_mb-option) setting, but I lean more toward "fail fast" and letting it crash, so we know something is not behaving as expected.

**Comment by eylenburg** [comment]
Thank you. Just wondering, what's the easiest way to change an existing Fly.io machine from 1024 MB to 256 MB?

**Comment by pcrockett** [comment]
No worries, and thanks for your ideas / feedback!

I edited my `fly.toml` file and ran `make deploy`. You should see my edits in the latest `fly.template.toml` on the main branch.

Also this does remind me that health checks are important, so I created a to-do item: https://github.com/pcrockett/mollysocket-fly/issues/3

**Comment by pcrockett** [comment]
I expect my bill to be under $2 this month. Since anything less than $5 will be waived, I think it's safe to say this is still within the free tier.
