### ISSUE TITLE
QR Code in the FOSS flavor with the merged UP support

### ISSUE THREAD

**Issue by whysofurious1** [pcrockett/mollysocket-fly#15]
Hi! First of all thank you for this repo, I am happily using it with my molly installation and it works perfectly!

So it seems that molly-UP is being deprecated and the UP support is merged in the main app (see https://github.com/mollyim/mollysocket/commit/64c1585299be2b987ceb16ba35dfac63f250a705 and https://github.com/mollyim/mollyim-android-unifiedpush/releases/tag/v7.23.1-1.up1).

I tried switching to the FOSS app but it seems that the only way I can activate unified push is by scanning a qr code, but I don't think I did that with this setup originally, and have no idea if the fly.io app can show that (do we need to assign an ip address?) Admittedly I haven't tried too hard to look into that apart from the docs here, so sorry if I missed something or if the question is redundant :)

**Comment by pcrockett** [comment]
Hey, thanks for the heads up. I noticed in the [latest mollysocket release](https://github.com/mollyim/mollysocket/releases/tag/1.5.4] it says:

> Print QR from the logs if webserver is false

That looks like they key. I don't have time to look into it now, however in the next days I plan to, and I'll update instructions here. For now I'll put a notice in the README.

**Comment by p1gp1g** [comment]
The QR code requires the VAPID key to be set up, which is not the case here. Is there any persistent storage somewhere ?

I can open a non-tested PR that should mostly work to help

**Comment by p1gp1g** [comment]
If someone can try it: https://github.com/pcrockett/mollysocket-fly/pull/16

**Comment by pcrockett** [comment]
I have things working with the new Molly app. Check out the instructions in the [molly-migration branch](https://github.com/pcrockett/mollysocket-fly/tree/molly-migration). I would really appreciate it if someone could test the new procedure to make sure I got everything right.

**Comment by pcrockett** [comment]
Ok, this is now [released](https://github.com/pcrockett/mollysocket-fly/releases/tag/v2.0.0). See the [migration guide](https://github.com/pcrockett/mollysocket-fly/blob/main/doc/MIGRATION.md) for details on how to migrate from the legacy Molly-UP app to Molly-FOSS.

Feedback welcome!

**Comment by whysofurious1** [comment]
Thanks for the quick fix! Will try it today or tomorrow at latest and let you know :)

**Comment by whysofurious1** [comment]
I went trough the migration process just now, qr code generation (even with transparent terminal), test notifications and other notifications seems to work on my end. Thanks!

A quick thing, it might be worth to add a reminder that if the deploy actions are enabled on github, the FLY_APP and FLY_DEPLOY_TOKEN secrets need to be updated as well, correct?

**Comment by pcrockett** [comment]
good call. thanks.
