### ISSUE TITLE
Thoughts about render.com as hosting option

### ISSUE THREAD

**Issue by mdehollander** [pcrockett/mollysocket-fly#5]
First thanks for making this. I was a bit reluctant with setting up the fly.io account since it needs a creditcard and I see that it might be possible to charge you in #1. At least it is something to keep an eye on. Therefore I looked if there is also another free hoster.  Heroku used to be a good choice, Hetzner is not free but cheap and I see Render.com also offers running docker vms in their free tier. What are the requirements for the mollysocket?

Did you look into render before choosing fly? I see that render.com does not require a credit card. But it does not allow to run private servers, not sure if that is needed or that is possible with fly.

Thanks for your thoughts!

**Comment by pcrockett** [comment]
Good questions.

> What are the requirements for the mollysocket?

I have been running mollysocket just fine for a while now using [1 CPU and 256 MB RAM](https://github.com/pcrockett/mollysocket-fly/blob/e2494023d65e925d3a544492868ba6411a2167d2/fly.template.toml#L17).

> Did you look into render before choosing fly?

No, not really. No particular reason; I see [Fly blog posts](https://fly.io/blog/) show up occasionally on [my favorite news aggregation site](https://lobste.rs/), but I rarely see anything about render.com. That's not to say Fly is better; I'm just more aware of Fly than Render.

> private servers

Are you referring to "air gap mode," or are you referring to managing your own private cloud virtual machines? I can't speak much about Render's offering there, but at least with Fly, we don't really have (or need) a full virtual machine. MollySocket is running in a container.

I know Heroku requires that you have a web service of some kind that accepts HTTP requests from the Internet. Fly does NOT have this restriction, which is awesome, and allows us to run MollySocket in "air gap mode." I have no idea if Render allows this use case or not.

> your thoughts

I'm pretty happy with Fly.io so far. If (when?) they start [enshittifying](https://en.wikipedia.org/wiki/Enshittification), I'll look for something else.

If you or someone else does find a solution for running on render.com, please do let me know! I'll be happy to link to it in the README.

**Comment by mdehollander** [comment]
Thanks for the details.

I found out that render.com also requires credit card information. I had a rpi here locally for a small NAS project and it was easy to run mollysocket via docker compose on it in air-gapped mode. For a few days the notifications using ntfy are working great. Happy with this simple setup. No need for a cloud service at this moment.

**Comment by pcrockett** [comment]
Awesome. Yeah if you have a device already and want to keep it up, then self-hosting is definitely the way to go. Thanks for checking out Render and letting me know.
